Build C# library for Thing proto
Uses instructions from https://rules-proto-grpc.com/en/latest/lang/csharp.html#csharp-proto-library

NOTE: rules_dotnet setup instructions [1] tell you to use the .NET 6 toolchain; however, Google's Protobuf NuGet package is not imported with .NET 6, which results in the following error when building thing_csharp_proto:

bazel-out/k8-fastbuild/bin/example/proto/thing_csharp_proto.dll_pb/Thing.cs(9,21): error CS0400: The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)

To workaround the error, I changed the toolchain to .NET 5 (5.0.404).

Known issue and long-term fix is in PR https://github.com/rules-proto-grpc/rules_proto_grpc/pull/174/

1. https://github.com/bazelbuild/rules_dotnet#setup